TARGET		:=	test
BUILD		:=	build
DATA		:=	data
SOURCES		:=	source
INCLUDES	:=	$(SOURCES) ../include

DEFINES		:= -g -O3 -Wall
LIBS		:= 
LDFLAGS		:= -L../../ -lbricks

export LD_LIBRARY_PATH	:= ../

-include ../../common.mk
-include ../../../common.mk
