#pragma once

#define BRICKS_VERSION_MAJOR 0
#define BRICKS_VERISON_MINOR 1
#define BRICKS_VERSION "0.1"

//#define BRICKS_CONFIG_LOGGING 1
//#define BRICKS_CONFIG_LOGGING_HEAVY 1
//#define BRICKS_CONFIG_LOGGING_MEMLEAK 1

//#define BRICKS_CONFIG_CPP0X 1
#define BRICKS_CONFIG_RTTI 1
#define BRICKS_CONFIG_STL 1

#define BRICKS_CONFIG_AUDIO_FFMPEG 1

#define BRICKS_CONFIG_COMPRESSION_LIBZIP 1

#define BRICKS_CONFIG_IMAGING_LIBPNG 1
#define BRICKS_CONFIG_IMAGING_FREETYPE 1
