#pragma once

#include "bricks/object.h"

#define BRICKS_ARGLIST_HEADER "bricks/internal/alloc.h"

#define BRICKS_ARGLIST_ENUM_CUSTOM(count, value) BRICKS_ARGLIST_ENUM_CUSTOM_(count, value)
#define BRICKS_ARGLIST_ENUM_CUSTOM_(count, value) BRICKS_ARGLIST_ENUM_ ## count(BRICKS_ARGLIST_ENUM_METHOD_CUSTOM, value)
#define BRICKS_ARGLIST_ENUM_METHOD_CUSTOM(n, v) const_cast<T ## n&>(v ## n)

#define BRICKS_ARGLIST_TYPES_NAMES BRICKS_ARGLIST_ENUM2(BRICKS_ARGLIST_COUNT, const T, & arg)
#define BRICKS_ARGLIST_ARGS BRICKS_ARGLIST_ENUM_CUSTOM(BRICKS_ARGLIST_COUNT, arg)

#include "bricks/internal/arglist.h"

#undef BRICKS_ARGLIST_TYPES_NAMES
#undef BRICKS_ARGLIST_ARGS
#undef BRICKS_ARGLIST_ENUM_CUSTOM
#undef BRICKS_ARGLIST_ENUM_CUSTOM_
#undef BRICKS_ARGLIST_ENUM_METHOD_CUSTOM

#undef BRICKS_ARGLIST_HEADER
