#pragma once

#define BRICKS_VERSION_MAJOR 0
#define BRICKS_VERISON_MINOR 1
#define BRICKS_VERSION "0.1"

//#define BRICKS_CONFIG_LOGGING
//#define BRICKS_CONFIG_LOGGING_HEAVY
//#define BRICKS_CONFIG_LOGGING_MEMLEAK

//#define BRICKS_CONFIG_CPP0X
#define BRICKS_CONFIG_RTTI
#define BRICKS_CONFIG_STL

//#define BRICKS_CONFIG_AUDIO_FFMPEG

#define BRICKS_CONFIG_COMPRESSION_LIBZIP

#define BRICKS_CONFIG_IMAGING_LIBPNG
#define BRICKS_CONFIG_IMAGING_FREETYPE
