find_package(ZLIB)

find_path(LIBZIP_INCLUDE_DIR_zh
	NAMES
	zip.h
	)

find_path(LIBZIP_INCLUDE_DIR_zch
	NAMES
	zipconf.h
	PATHS
	/lib/libzip/include
	)

find_library(LIBZIP_LIBRARY
	NAMES
	zip
	)

if (LIBZIP_INCLUDE_DIR_zh AND LIBZIP_INCLUDE_DIR_zch AND LIBZIP_LIBRARY)
	set(LIZIP_INCLUDE_DIRS "${LIBZIP_INCLUDE_DIR_zh};${LIBZIP_INCLUDE_DIR_zch};${ZLIB_INCLUDE_DIRS}")
	set(LIBZIP_LIBRARIES ${LIBZIP_LIBRARY} ${ZLIB_LIBRARIES})
	set(LIBZIP_FOUND true)
endif()
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LibZip  DEFAULT_MSG  LIBZIP_LIBRARIES  LIBZIP_INCLUDE_DIRS)
