include(LibFindMacros)

libfind_package(LIBZIP ZLIB)

find_path(LIBZIP_INCLUDE_DIR_zh
	NAMES
	zip.h
	)

find_path(LIBZIP_INCLUDE_DIR_zch
	NAMES
	zipconf.h
	PATHS
	/lib/libzip/include
	)

find_library(LIBZIP_LIBRARY
	NAMES
	zip
	)

if (LIBZIP_INCLUDE_DIR_zh AND LIBZIP_INCLUDE_DIR_zch)
	set(LIBZIP_INCLUDE_DIRS "${LIBZIP_INCLUDE_DIR_zh};${LIBZIP_INCLUDE_DIR_zch}")
endif()

set(LIBZIP_PROCESS_INCLUDES LIBZIP_INCLUDE_DIR ZLIB_INCLUDE_DIRS)
set(LIBZIP_PROCESS_LIBS LIBZIP_LIBRARY ZLIB_LIBRARIES)
libfind_process(LIBZIP)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LibZip  DEFAULT_MSG  LIBZIP_LIBRARY  LIBZIP_INCLUDE_DIRS)
